# Site settings
title: Your GitHub Page Title
description: A short description of your site
baseurl: "" # The subpath of your site, e.g. /blog. Leave blank for root directory.

author: 
  name: Abhishek Rithik Origanti
  email: your-email@example.com

# Theme
theme: minima

# Customization options for Minima theme
minima:
  social_links:
    github: https://github.com/yourusername
    linkedin: https://www.linkedin.com/in/yourprofile/
    twitter: https://twitter.com/yourhandle

# Homepage Settings
permalink: /index.html # Use custom HTML as homepage

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude files and directories
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md

# Additional settings
paginate: 10 # Number of posts per page
paginate_path: "/page:num/"
